# -*- coding: utf-8 -*-
"""Trans

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1918BGrphtibsnDdirbk6r8-8Qovj_xbV
"""

#!pip install googletrans

from googletrans import Translator
import pandas as pd

def TransCol(df,col1,col2):
  translator = Translator()
  
  df['SD_translated'] = df[col1].apply(translator.translate, dest='en').apply(getattr, args=('text',))
  df['D_translated'] = df[col2].apply(translator.translate, dest='en').apply(getattr, args=('text',))
  return df